### ISSUE TITLE
Strikes Panel is completely broken

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#1]
Current situation, with no mods except TAHC. Issue seems to be Grid limit is applied to all buttons, as minimum instead maximum

![image](https://user-images.githubusercontent.com/4083812/218342809-d9450596-f681-40e3-9b65-2814f16bcfc7.png)

Bad Buttons + and - to edit spell slots

![image](https://user-images.githubusercontent.com/4083812/218342886-d48c1a9e-b91d-4ab7-ab8f-5331840890d3.png)

**Comment by Larkinabout** [comment]
That's not broken, it's just the impact of using a grid layout on buttons with very variable widths. Grid layout currently uses the median width plus a bit extra. Using the max content would look just as bad with overly wide buttons.

In terms of spell slot buttons, I'm planning to move those to the subtitle info, so they're not impacted by the grid layout. For strikes, I just wouldn't use a grid layout as it works better without.

In the future, I expect I'll add in dual widths, such as median width and half median width, but for now it's a choice between grid layout for all or none.

**Comment by apoapostolov** [comment]
Okay first off, the problem was that I had Use Grid on in my mod settings, causing the whole interface (all sections) to be treated as grid. This was fixed by turning that option off. 

I will open a separate issue for all the problems I think there are with the current implementation of Attacks.
