### ISSUE TITLE
Token hud doesn't render in PF2e for characters will spells

### ISSUE THREAD

**Issue by Velerak** [Larkinabout/fvtt-token-action-hud-pf2e#100]
![Screenshot 2023-11-18 230234](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/70804131/dc1798f6-9192-468c-b6d4-4a6ad9ffbc75)

**Comment by Velerak** [comment]
This is with the new kingmaker campaign loaded, just in case that makes any difference :)

**Comment by Khybersghost** [comment]
+1

**Comment by itastelikelove** [comment]
Same issue, no kingmaker campaign but still only affects PCs and NPCs with spells

**Comment by Larkinabout** [comment]
Fixed in 1.5.3.
