### ISSUE TITLE
Comparisons against 5.* system versions provide incorrect results in version 5.10.*

### ISSUE THREAD

**Issue by Cuingamehtar** [Larkinabout/fvtt-token-action-hud-pf2e#102]
This is evident when displaying strike MAP values.
The module thinks that `game.system.version < "5.2.0"` is true due to string comparison, which I guess isn't very suited for semantic version comparison.

**Comment by soaringthor** [comment]
I was able to fix this by defining a new const: `systemVersion = coreModule.api.Utils.getModuleVersionParts(game.system.version)` and then doing comparisons like `if ((this.systemVersion.major < 5) || (this.sytemVersion.major == 5 && this.systemVersion.minor < 2))`. game.system.version appears in both the RollHandler and ActionHandler so I'm not sure where to best put this const. I'm not a coder so I'm hoping this is an easy enough fix for someone who knows what they're doing!

**Comment by Cuingamehtar** [comment]
Alternatively, the required PF2e version for this module can be updated so that the check is no longer necessary.

**Comment by Larkinabout** [comment]
Fixed in 1.5.4.
