### ISSUE TITLE
Incorrect labels & missing kineticist impulses following 2e system update

### ISSUE THREAD

**Issue by wealthbeyondmeasure** [Larkinabout/fvtt-token-action-hud-pf2e#103]
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/106809509/e851e5df-b00e-4398-8c5f-609985c3ce76)

After the 2e system update, there are exposed text strings instead of text labels for some of the categories on the drop down HUD.

In addition, the Kineticist's Elemental Blasts no longer show up under the Strikes category - there's the toggle for 1 or 2 actions, but no actual blasts to use.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/106809509/bb8892c4-495f-4247-b4af-439be4c5d3f1)

**Comment by soaringthor** [comment]
For the Feats and Spells labels, I found that these labels were removed from the pf2e en.json localization file: https://github.com/foundryvtt/pf2e/pull/11772
Maybe Token Action HUD PF2 needs to replace `PF2E.TabFeatsLabel` with `PF2E.Item.Feat.Plural` and `PF2E.SpellLabelPlural` with `PF2E.Item.Spell.Plural`?

**Comment by xKillerbees** [comment]
Came here to report this too :P

**Comment by soaringthor** [comment]
More labels moving... https://github.com/foundryvtt/pf2e/pull/11995

**Comment by Larkinabout** [comment]
Fixed in 1.5.4.
