### ISSUE TITLE
'Blank ARMY' when no token selected

### ISSUE THREAD

**Issue by uniwars** [Larkinabout/fvtt-token-action-hud-pf2e#105]
Hi, I noticed that when I have no token selected as GM I see a "Blank ARMY" and it seems to come from token action HUD (tested with no other modules enabled)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/65986545/6425b164-3898-4a6f-bf74-39f2ae090448)

Foundry V11.315
System Pathfinder 2e 5.11.5
Token action HUD Core 1.5.2
Token action HUD Pf2e 1.5.4

**Comment by Larkinabout** [comment]
If it's Token Action HUD, then it might be because you have an actor callee 'Blank ARMY' assigned to your user. You can unassigned it from the player list down in the bottom-left of the screen.

**Comment by uniwars** [comment]
Oh yeah sorry, I didn't know GM could also have assigned actor
