### ISSUE TITLE
Rolling initiative from the Attributes menu does not honor the roll dialog option as of PF2e 5.12.3

### ISSUE THREAD

**Issue by Silvertower** [Larkinabout/fvtt-token-action-hud-pf2e#109]
token-action-hud uses 'showRollDialogs' when calling #setRollOptions() but needs to use 'showCheckDialogs' due to a breaking change.

From roll-handler.js:

        #setRollOptions () {
            const skipDefault = !game.user.settings.showRollDialogs
            this.rollMode = (this.ctrl) ? (game.user.isGM) ? 'gmroll' : 'blindroll' : null
            this.skipDialog = (this.shift) ? !skipDefault : skipDefault
        }

To fix, change it to:

        #setRollOptions () {
            const skipDefault = !game.user.settings.showCheckDialogs
            this.rollMode = (this.ctrl) ? (game.user.isGM) ? 'gmroll' : 'blindroll' : null
            this.skipDialog = (this.shift) ? !skipDefault : skipDefault
        }

As a temporary workaround, this can be fixed in token-action-hud-pf2e.min.js by replacing the following (entire) string:

showRollDialogs

With:

showCheckDialogs

**Comment by Larkinabout** [comment]
Hi @Silvertower, do you want to submit a pull request and I'll merge it in?

Also, if you're interested, I'm looking for someone to take over the development of Token Action HUD Pathfinder 2 as I don't play Pathfinder 2 enough to support the regular updates. Let me know if you'd be interested.

**Comment by Silvertower** [comment]
Hello,

My knowledge of JavaScript is next to none, as my only experience is with
backend development. I'd be of little help, but I can submit some pull
requests for now.

Thanks,

Silvertower
