### ISSUE TITLE
Bug : Unable to cast spell from HUD since 5.12.x

### ISSUE THREAD

**Issue by uniwars** [Larkinabout/fvtt-token-action-hud-pf2e#118]
Hi, casting from the HUD may be impossible for some spells 'prepared I believe) getting this error in console :

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/65986545/bbd5d89a-45f4-485c-8ad1-260ea77edd99)

I believe Pf2e Interactive Token Tolltip had the same issue and fixed it ina  recent module update

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/65986545/055951f7-9b85-4da0-8282-17b271161e74)

Seeing this patch note there may be a related issue with action as well.

**Comment by uniwars** [comment]
[fvtt-Actor-valira-O93LozChjVPrlvnf.json](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/files/13929475/fvtt-Actor-valira-O93LozChjVPrlvnf.json)

Here is my actor, the enlarge/air walk spells doesn't work but other works fine

**Comment by uniwars** [comment]
it seems to be heightened spells that doesn't work

**Comment by Larkinabout** [comment]
Seems to be indirectly fixed in 1.5.5. Try it out and let me know.
