### ISSUE TITLE
[BUG] Use Weapon Label instead of Slug

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-pf2e#12]
> > Heres another interesting one, two weapons, different names, but for some reason the HUD shows them as one(using the weapon id perhaps?) happens with ranged combat module, also happens without the module
> 
> It uses the slug currently, which I suspect is the same for these two items? Perhaps that happens when an item is added to an actor and then renamed. I should be able to change it to the name instead without too much issue. It can't use the item id as otherwise the GM's HUD gets filled up with empty groups of weapons for every monster they've clicked on.

changing to name will help a lot

_Originally posted by @roi007leaf in https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/67

**Comment by tehguitarist** [comment]
This may have something to do with this issue: https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/issues/110

No solutions, just some insights. (Ironically found it when looking to see if there was anything about the original issue thread issue on the offending module).

**Comment by JDCalvert** [comment]
As a workaround for this issue, the PF2e system has recently added the ability to edit the slug of an item, which allows Token Action HUD to see them as different items.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.3.0.
