### ISSUE TITLE
HUD working for some PC's but not for others (PF2E)

### ISSUE THREAD

**Issue by Jfrankfl** [Larkinabout/fvtt-token-action-hud-pf2e#128]
^^Title
There is an error coming from the console log for some PCs but not for others, resulting in some PCs not having accessible HUD for both my players and I. Here is the error and please let me know if any other info needs to be provided.

Have attempted to remove every module aside from HUD and its dependencies and still error persists.

Attached is the error, the module version info, the pathfinder 2e system rule version and the foundaryVTT build

![Error](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/159719270/f57f5e77-740d-4535-80e6-397b7bf602ba)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/159719270/e2637680-0422-45fd-a020-a3fd4ccfc6df)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/159719270/d416dc64-991f-444e-8395-065e5945b0f9)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/159719270/4bc7aab4-d1c9-46cd-aecd-ae60b2c26e4a)

**Comment by Silvertower** [comment]
As of version 1.5.5, PF2e system 5.12.7 or later is required. I see you are running 5.9.5. Please update PF2e and then check if the error persists.

**Comment by Jfrankfl** [comment]
> As of version 1.5.5, PF2e system 5.12.7 or later is required. I see you are running 5.9.5. Please update PF2e and then check if the error persists.

Will do so now

**Comment by Jfrankfl** [comment]
Would appear issue has been fixed, thanks!
