### ISSUE TITLE
Kineticist toggles no longer show up under Strike

### ISSUE THREAD

**Issue by varun4513** [Larkinabout/fvtt-token-action-hud-pf2e#135]
Foundry v11 build 315
PF2E - 5.14.3
Token Action HUD Core - 1.5.3
Token Action HUD Pf2e - 1.5.10

Since one of the recent updates, the Elemental Blast (1 or 2 Action) and the Weapon Infusion Trait toggles no longer show under Strikes, when Weapon Infusion is active. I tried editing them in manually, but don't see anything under Weapon Infusion except the Feat itself. The damage type toggles are still there under Elemental Blast. PF2E Discord said Kineticist had been updated with 5.14.

**Comment by Silvertower** [comment]
Thanks for the report. Many things aren’t working after the 5.14 update. Will investigate when back from vacation.

**Comment by Silvertower** [comment]
This will be fixed in the next version of Token Action HUD PF2e.

**Comment by Silvertower** [comment]
Fixed in Token Action HUD PF2e version 1.5.12.

**Comment by varun4513** [comment]
Working for me, thank you!
