### ISSUE TITLE
[Bug] Shortsword does not seem to be recognized as a weapon under Action -> Strikes; cannot add Melee option to it.

### ISSUE THREAD

**Issue by Aragith** [Larkinabout/fvtt-token-action-hud-pf2e#14]
Cannot seem to get the Shortsword weapon to show its Melee attacks, sheathe, draw, etc. Only option it gives while editing is to add Shortsword to it again and this goes on recursively, as if the module does not recognize the character has a Shortsword in their inventory. See pictures below. I tried it on several different characters.

![image](https://user-images.githubusercontent.com/124524014/220255666-76d1e662-837e-4432-8080-f784408fbc9d.png)
![image](https://user-images.githubusercontent.com/124524014/220256097-6e48ac85-e29f-44c8-a5fe-bf96e7126a97.png)
![image](https://user-images.githubusercontent.com/124524014/220256422-2231bcbf-87f9-423a-81af-21d95389b748.png)

**Comment by Larkinabout** [comment]
I've not managed to replicate this issue on my end and the Shortsword from the compendium works as expected.

Can you export the actor data and attach it to this issue and I'll take a look.

**Comment by Aragith** [comment]
It might be an underlying issue with that one world. The same actor in a different world works fine. I will try and investigate to see if it is some weird module interaction, or if the world has some corruption because of the server instability over the past weekend.

**Comment by Aragith** [comment]
Here is the actor data if you want to look.
[fvtt-Actor-saffir.zip](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/files/10819398/fvtt-Actor-saffir.zip)

**Comment by Aragith** [comment]
It looks like the issue was due to world corruption of some sort. A fresh new world with all the same modules and even the same imported actors works fine.
