### ISSUE TITLE
Request: Groups for Encounter, Exploration and Downtime actions

### ISSUE THREAD

**Issue by samdavidbarrie** [Larkinabout/fvtt-token-action-hud-pf2e#146]
My players and I like to use the Token Action HUD, but find that we are bouncing between using the Basic Action Macros and Token Action HUD, mostly when trying to choose actions/activities in different spheres of play (encounter, exploration and downtime)

I would find it very helpful to have a group that lists all skill actions for an encounter, a group that lists all the exploration actions (regardless of skill, things like Affix a Talisman etc) and one group that lists all downtime activities.

At the moment, there is no workaround if I wish to make these groups myself since skill-less actions often aren't supported, exploration actions like Defend do not seem to have a way to get on the Token Action HUD.

Of course, if there were a way to add Basic Action Macros to the HUD (as I believe it used to be at one point) that would be awesome!

**Comment by Silvertower** [comment]
I'm not sure what any of this means, but if someone wants to make a pull request to add such functionality, I can take a look at it. At this time, Token Action HUD PF2E is more or less in maintenance mode to keep things working.
