### ISSUE TITLE
Foundry Version 12 Compatibility

### ISSUE THREAD

**Issue by thebrownjumper** [Larkinabout/fvtt-token-action-hud-pf2e#147]
@Silvertower you mention and confirm that Action HUD PF2e and Core + other HUD's are now basically in twilight mode.

Does this imply that Foundry version 12 compatibility is off the table?

Would be good to know as the big migration from 11 is likely to start for most in PF2e the next couple of months (or so).

Appreciate you stepping in to keep the lights on by the way 💯

**Comment by Silvertower** [comment]
I have dome some preliminary testing on Foundry v12. Beyond deprecation warnings for v14, almost everything seems to work out of the box, except for Hero Points, which I haven't looked into. I am currently waiting for Token Action Hud Core to complete v12 compatibility before updating TAH PF2E for v12.

**Comment by thebrownjumper** [comment]
That sounds absolutely great that there are no (or not fundamental) breaking changes...  I'll continue watch in anticipation for TAH PF2e to cross over to 12.

Thanks again @Silvertower 👍🏼

**Comment by Silvertower** [comment]
v12 compatibility was added in 1.5.16
