### ISSUE TITLE
Kineticist Elemental Blast isnt showing all three attacks with the Multiple Attack Penalty (MAP) options 

### ISSUE THREAD

**Issue by Pilsberry** [Larkinabout/fvtt-token-action-hud-pf2e#150]
Greetings,

Two of my players are kineticists that dont seem to be showing their 3 MAP attacks from their Elemental Blast abilities. It only shows the full attack bonus and MAP -5, but not the MAP -10 3rd action. We are using Token Action HUD Pathfinder 2e module for this.

As a matter of record, I'm a handyman contractor by trade and not a software coder genius like many of you are. Go easy on me and be patient while I try to understand anything you are asking me. 

Matt
![Screenshot_2024-06-09_235658](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/172456211/727c967c-d124-4c40-823d-5159f474b3d9)

**Comment by Silvertower** [comment]
Thank you for the report.
What version of Token Action HUD PF2E are you using?
What version of Pathfinder 2E System are you using?
What version of Foundry VTT are you using?
Can you provide detailed steps on how to reproduce this issue?
Can you upload an export of a character that has this issue? You can do this by right-clicking on the character in Foundry and choosing export, which will save a json file. You can upload that file to this issue and I will take a look.

**Comment by Pilsberry** [comment]
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/172456211/e0d0cdf3-f802-433c-9d4c-c1f494b8ee75)
Pathfinder 2E System version 5.12.3
Foundry VTT version 11 Build 315

I built a level 1 Test Kineticist thinking that my players screwed up theirs somehow, but even the test kineticist is showing the same issue. 
Step by Step Guide
1) Create Actor/PLayer Character
2)Click on Class Search icon, drag Kineticist into the Class bar. Pick Dual Gate. Pick an 2 elements (I chose Fire and Earth as well as my other players). 
3) Choose an Impulse Feat. I chose Flying Flame and Armor in Earth.
4) Drag the actor onto a map.
5) Go into the 2nd tab for actions and hit the Use button for Channel ELements. 
6) Apply the effect to the actor from the chat bar
7) Go to the Strikes in the HUD and you will see that only 2 Multiple Attack Penalty actions are being shown.
[fvtt-Actor-test-kinteticist-Jqxf1vrNDtHUyxC4.json](https://github.com/user-attachments/files/15844769/fvtt-Actor-test-kinteticist-Jqxf1vrNDtHUyxC4.json)

Hope that helps!

**Comment by Silvertower** [comment]
Hi,
This issue is due to the very old version of PF2e system and Foundry, and
probably also Token Action HUD PF2e.
Please update PF2e system to 5.16.1 and Token Action HUD PF2e to 1.5.15.
Here's the character, imported into those versions:
[image: image.png]

**Comment by Pilsberry** [comment]
Well now I feel stupid. Thank you for your efforts! I love the app!
