### ISSUE TITLE
HUD Core Compatibiltiy

### ISSUE THREAD

**Issue by Keatnisher** [Larkinabout/fvtt-token-action-hud-pf2e#151]
Hi, I'm receiving the banner error message to "update" my Token Action HUD Core module to 1.5.5 in order for HUD PF2e to work - but my Core module is actually ahead at 1.5.6. Can this be fixed to check for _at least_ version 1.5.5? 

Also, this appears to make HUD PF2e to not display - unless this is related to another issue.

**Comment by Silvertower** [comment]
Hello. I don't know what that means, unfortunately. TAH2E doesn't produce banner messages itself.

**Comment by Keatnisher** [comment]
Oh, my bad - this is the error I'm receiving:

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/26535174/623164ac-3f98-4b7e-8d78-3b860cffe9a6)

**Comment by Silvertower** [comment]
This looks like a message from Token Action HUD Core. I will see if I can fix it.

**Comment by Larkinabout** [comment]
It means the system module is set to require a specific version of Token Action HUD Core.

Best bet is to set the required version to 1.5 rather than 1.5.X as the X releases are not intended to include breaking changes for system modules and X.X releases are much rarer.

**Comment by Silvertower** [comment]
Cool. I know nothing about this stuff.

**Comment by Keatnisher** [comment]
Is it as simple as removing the maximum of 1.5 here in module.json? Or is a set max required?

"requires": [
      {
        "id": "token-action-hud-core",
        "type": "module",
        "compatibility": [
          {
            "minimum": "1.5.5",
            "maximum": "1.5",
            "verified": "1.5.5"
          }
        ]
      }

**Comment by Larkinabout** [comment]
Yeah, I wouldnt have expected it. It's mentioned here for those developing a system module from scratch: https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module#requiredcoremoduleversion

**Comment by Larkinabout** [comment]
> Is it as simple as removing the maximum of 1.5 here in module.json? Or is a set max required?
> 
> "requires": [ { "id": "token-action-hud-core", "type": "module", "compatibility": [ { "minimum": "1.5.5", "maximum": "1.5", "verified": "1.5.5" } ] }

No, but @Silvertower is on it, so you can just download the release when it happens.

**Comment by Silvertower** [comment]
Fixed in Token Action HUD PF2E version 1.5.17.

**Comment by Keatnisher** [comment]
Everything's working now! Thanks for the quick response :)
