### ISSUE TITLE
TAH PF2e no longer working with PF2e system 6.5.0 update TAH Core 2.0.

### ISSUE THREAD

**Issue by jasonckramer** [Larkinabout/fvtt-token-action-hud-pf2e#155]
Looks like PF2E TAH module needs to be made compatible with PF2e system 6.5.0 and TAH Core 2.0.

**Comment by Silvertower** [comment]
I am working on adding support for PF2e system 6.5.0. For now, TAH PF2e will need to stay on TAH Core 1.5.7 indefinitely. I recommend users lock their TAH Core version on 1.5.7 until such a time as TAH PF2e can be modified to support TAH Core 2.0+.

**Comment by GameScripting** [comment]
I was able to downgrade after updating, by

* uninstalling `Token Action HUD Core` (TAH Core) and then
* re-installing it using this manifest URL (latest 1.X version):
`https://github.com/Larkinabout/fvtt-token-action-hud-core/releases/download/1.5.7/module.json`
* locking the TAH Core module:

![actionhud](https://github.com/user-attachments/assets/2d96eeda-7d40-44f6-8345-8cee7f023423)

Now it works again 🎉

**Comment by Xemonym** [comment]
Life saver; thank you!

**Comment by Larkinabout** [comment]
Added in 2.0.0.
