### ISSUE TITLE
HUD appears behind default Foundry VTT elements with default positioning after 2.0 update

### ISSUE THREAD

**Issue by Silvertower** [Larkinabout/fvtt-token-action-hud-pf2e#158]
![image](https://github.com/user-attachments/assets/1d6bdda8-7e4c-46c3-aa97-80a3f7880a23)

Currently researching if it is possible to set the default HUD position for Token Action HUD PF2e. So far, I have been unable to determine where HUD position is stored (doesn't appear to be under core/storage, nor in the browser local storage for the site. Might be stored in Foundry's own internal data, but uncertain as of yet how to access it.

**Comment by Larkinabout** [comment]
Does resetting the layout do it? The position is saved in a user flag. I suspect somewhere along the line it's defaulted to x0, y0.

**Comment by Silvertower** [comment]
I tried resetting, but it does indeed default to 0,0. Same experience when installing it fresh and using a fresh browser.

**Comment by bhibb** [comment]
I can confirm that this is happening for me as well.

**Comment by Silvertower** [comment]
Still researching. Looks like something that needs to be addressed in core though.

I found that editing token-action-hud-core.min.mjs and replacing:

this.hudPosition={top:this.defaultTopPos,left:this.defaultLeftPos}

with

this.hudPosition={top:80,left:150}

and then using the Reset Layout (must have a token selected, or an error will be generated) option in Token Action HUD Core's Layouts window (click on the Layouts button to access) will set the HUD position to the normal default position. The Reset All Layouts option doesn't work.

Additionally, I still cannot find where the position is stored, as it is not located under storage in the module directory.

defaultTopPos and defaultLeftPos come from token-action-hud-core.min.mjs.map, if I understand correctly, and look okay in that file, but for some reason don't seem to be working.

**Comment by Silvertower** [comment]
Fixed in Core https://github.com/Larkinabout/fvtt-token-action-hud-core/releases/tag/2.0.6
