### ISSUE TITLE
[FEATURE] Make item descriptions appear one line, as in old TAH

### ISSUE THREAD

**Issue by weepingminotaur** [Larkinabout/fvtt-token-action-hud-pf2e#17]
Right now, if you have an item in the Actions category, like for example Rapier, it spills over onto multiple lines, making everything look ugly and cluttered. Please consider going back to the old display for Token Action HUD, which was much more compact and easy on the eyes.

**Comment by Larkinabout** [comment]
You might have grid mode enabled. You can disable it from the module setting screen, which enables it for all actions, or from the individual categories by unlocking the HUD and right-clicking the top line buttons. You can also set a custom width if the actions are still wrapping.

The separate lines for auxiliary actions and variants is another matter that you will be able to resolve for yourself in the next release.
