### ISSUE TITLE
[BUG] Signature Spells not being recognized in heightened slots. 

### ISSUE THREAD

**Issue by vespertineSiren** [Larkinabout/fvtt-token-action-hud-pf2e#18]
### Issue
- I have a player that has a summon spell at level 1 that is auto heightened. 
- That player has no spell slots left for level 1. (0/3 slots available)
- When that player tried to use that summon spell auto heightened to 6th (2/2 slots available), the module complains that there are no spell slot left to cast

| Spells | Error from clicking high spell slot |
|--|--|
| <img width="843" alt="Screenshot 2023-03-06 at 11 38 50 AM" src="https://user-images.githubusercontent.com/27742105/223213522-8c3fbd35-b53d-4d87-85b1-468a3d60429a.png">| <img width="1240" alt="Screenshot 2023-03-06 at 11 38 59 AM" src="https://user-images.githubusercontent.com/27742105/223213589-2a237324-7cab-4d2f-a87c-82f231f5b626.png"> |

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.3.0.
