### ISSUE TITLE
Proposals for Improvement of Default PF2 Setup

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#2]
[ ] Rename Attacks to Strikes
[ ] Add Saves back as core section, they used to be their own section -- people are used to this
[ ] Put Skills and Saves before Attributes

**Comment by Larkinabout** [comment]
The default configuration is mimicking the character sheet tabs and positions, e.g., Attributes being everything on the left of the character sheet, strikes and actions being under the Actions header, etc.

With the HUD layout being fully customisable for experienced users, I'm inclined to leave it this way for new users who are going straight from the character sheet to the HUD. Eventually people used to the original layout will be outnumbered by users only familiar with this layout or the character sheet and it's really those people that need to catered for by a default configuration.

**Comment by Larkinabout** [comment]
FYI, if anyone is concerned about the time sink for setting up everyone's HUDs like the original, you can set up one and use the `game.tokenActionHud.copy` function to quickly copy it to other users.

**Comment by tehguitarist** [comment]
This one took me aback too at first. Is attributes the official name for the rollable checks on the left? I think of attributes as being strength, dex, con etc. That said, I can't think of a better name offhand. I'll have a look at the core rulebook and see if there's any guidance there.

**Comment by Larkinabout** [comment]
Strength, Dexterity, etc., are technically ability scores. I don't think there's an official name for all the other bits, like Initiative and Perception, though the Pathfinder 2 system on Foundry VTT groups them into 'Attributes', so that's what I went with:
![image](https://user-images.githubusercontent.com/105953297/218423148-2ea7011d-1c62-4fa9-8c0c-20972e0e8a87.png)

**Comment by apoapostolov** [comment]
> The default configuration is mimicking the character sheet tabs and positions, e.g., Attributes being everything on the left of the character sheet, strikes and actions being under the Actions header, etc.

@Larkinabout I would highly suggest that you don't change the preset from PF2 in TAH for TAHC plugin. People are greatly used to the information being presented in specific way will have a culture shock with moving to TAHC PF2 plugin, even for the smallest of changes I have players begging to go back to the old mod (and there are many). Also, the order in TAH was based on usability and importance of data (left to right) rather than character sheet ordering of elements. That is a completely different use case and Character Sheet is based on physical sheet order a lot more than usability.

True it is that we can remake the interface now to replicate the old positioning which is fine, and passing setup to other players can be done (though I hope you improve on the usability of this, rather than a macro passed in between power users) but you will run int he issue that rather than new users, you will have a lot of disgrunted old users (in fact, DM with their own disgruntled old users) who will have to redo the interface, or sit on the old mod untiil it stops working in some major version.

**Comment by apoapostolov** [comment]
Just to add, I am very happy with the extreme customizability. Playing with TAHC I was able to put saves and skills in a single section based on actual usability. Great work @Larkinabout 

![image](https://user-images.githubusercontent.com/4083812/218452066-c5382213-a78d-44f4-9bd8-86b60f44c62e.png)

**Comment by Ironxxx** [comment]
I split off Saves into their own tab, considering how often they're accessed it seems sensible but it's also very easy to do.

I would like to request that all Conditions are default in alphabetical order however.

**Comment by Larkinabout** [comment]
> I would like to request that all Conditions are default in alphabetical order however.

That'll come with Larkinabout/fvtt-token-action-hud-core#85

**Comment by apoapostolov** [comment]
@Larkinabout feel free to close this issue if you want. While not exactly ideal (2 lines instead of one, but 1 line if the weapon is sheathed) the current situation is workable. If there are improvements needed to current layout, I will open separate issues.
