### ISSUE TITLE
[BUG] Conditions being listed twice

### ISSUE THREAD

**Issue by DuskyVoltage** [Larkinabout/fvtt-token-action-hud-pf2e#21]
![image](https://user-images.githubusercontent.com/9156437/226935515-de7ff9e5-b27f-4b54-82cd-e53f659f7dc9.png)

Core: v1.2.3
Pf2e: v0.1.1

Unlike Larkinabout/fvtt-token-action-hud-core#87 this bug seems exclusive to the effects tab.

Conditions are being listed twice in the effects tab. Occurs even in a fresh world with only Core / Pathfinder 2e / lib - Color Settings active.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.3.0.
