### ISSUE TITLE
[BUG] Selecting multiple tokens when one is a lootable item breaks the action hud, and causes it to stop rendering.

### ISSUE THREAD

**Issue by tehguitarist** [Larkinabout/fvtt-token-action-hud-pf2e#22]
**Describe the bug**
When selecting multiple tokens, and one of them is a Loot actor (though I wouldn't be surprised if Hazard actors do the same thing) the HUD breaks, and stops rendering all together. It can be selected individually, it seems to just be when trying to calculate collected skills (as these actors don't have any). I thought this is more of a PF2e issue given the type of actors, but could just be simple error handling in core.

**Steps to reproduce**
1. Ceate a few regular actors
2. Create a loot actor
3. Select multiple actors (including loot actor and regular actors)

**Versions:**
- Token Action HUD Core: 1.2.3
- Token Action HUD System: PF2e 0.1.1
- System: PF2e 4.9.3
- Foundry VTT: 10.291
- Browser: Edge & Firefox

**Error 1:**
Uncaught (in promise) TypeError: this.actors is undefined
[Detected 2 packages: token-action-hud-pf2e, token-action-hud-core]
    _getSharedSkills https://tehguitarist.chickenkiller.com/modules/token-action-hud-pf2e/scripts/token-action-hud-pf2e.min.js:1
    _buildSkills https://tehguitarist.chickenkiller.com/modules/token-action-hud-pf2e/scripts/token-action-hud-pf2e.min.js:1
    _buildMultipleTokenActions https://tehguitarist.chickenkiller.com/modules/token-action-hud-pf2e/scripts/token-action-hud-pf2e.min.js:1
    buildSystemActions https://tehguitarist.chickenkiller.com/modules/token-action-hud-pf2e/scripts/token-action-hud-pf2e.min.js:1
    _buildSystemActions https://tehguitarist.chickenkiller.com/modules/token-action-hud-core/scripts/token-action-hud-core.min.js:1
    buildActionList https://tehguitarist.chickenkiller.com/modules/token-action-hud-core/scripts/token-action-hud-core.min.js:1

**Error 2:**
Uncaught (in promise) TypeError: this.actors is undefined
[Detected 3 packages: token-action-hud-pf2e, token-action-hud-core, lib-wrapper]
    _getSharedSkills token-action-hud-pf2e.min.js:1
    _buildSkills token-action-hud-pf2e.min.js:1
    _buildMultipleTokenActions token-action-hud-pf2e.min.js:1
    buildSystemActions token-action-hud-pf2e.min.js:1
    _buildSystemActions token-action-hud-core.min.js:1
    buildActionList token-action-hud-core.min.js:1
    _updateHud token-action-hud-core.min.js:1
    update token-action-hud-core.min.js:1
    <anonymous> token-action-hud-core.min.js:1
    #call foundry.js:724
    callAll foundry.js:681
    control foundry.js:25329
    selectObjects foundry.js:31230
    selectObjects foundry.js:31230
    _onDragLeftDrop foundry.js:24458
    callback foundry.js:27813
    _handleDragDrop foundry.js:28214
    _handleMouseUp foundry.js:28184
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerUp interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerComplete interaction.min.mjs:8
    onPointerUp interaction.min.mjs:8
    addEvents interaction.min.mjs:8
    setTargetElement interaction.min.mjs:8
    r interaction.min.mjs:8
    initPlugins core.min.mjs:8
    r core.min.mjs:8
    create core.min.mjs:8
    ro core.min.mjs:8
    e app.min.mjs:8
    #createApplication foundry.js:23356
    initialize foundry.js:23258
    initializeCanvas foundry.js:8094
    setupGame foundry.js:7929
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
[token-action-hud-pf2e.min.js:1:12672](https://tehguitarist.chickenkiller.com/modules/token-action-hud-pf2e/scripts/token-action-hud-pf2e.min.js)
    _updateHud token-action-hud-core.min.js:1
    AsyncFunctionThrow self-hosted:814
    (Async: async)
    update token-action-hud-core.min.js:1
    <anonymous> token-action-hud-core.min.js:1
    #call foundry.js:724
    callAll foundry.js:681
    control foundry.js:25329
    selectObjects foundry.js:31230
    forEach self-hosted:203
    selectObjects foundry.js:31230
    _onDragLeftDrop foundry.js:24458
    _onDragLeftDrop self-hosted:1359
    callback foundry.js:27813
    _handleDragDrop foundry.js:28214
    _handleMouseUp foundry.js:28184
    _handleMouseUp self-hosted:1359
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerUp interaction.min.mjs:8
    <anonymous> self-hosted:1359
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerComplete interaction.min.mjs:8
    onPointerUp interaction.min.mjs:8
    <anonymous> self-hosted:1359
    (Async: EventListener.handleEvent)
    addEvents interaction.min.mjs:8
    setTargetElement interaction.min.mjs:8
    r interaction.min.mjs:8
    initPlugins core.min.mjs:8
    r core.min.mjs:8
    create core.min.mjs:8
    ro core.min.mjs:8
    e app.min.mjs:8
    #createApplication foundry.js:23356
    initialize foundry.js:23258
    initializeCanvas foundry.js:8094
    InterpretGeneratorResume self-hosted:1822
    AsyncFunctionNext self-hosted:810
    (Async: async)
    setupGame foundry.js:7929
    InterpretGeneratorResume self-hosted:1822
    AsyncFunctionNext self-hosted:810
    (Async: async)
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    InterpretGeneratorResume self-hosted:1822
    AsyncFunctionNext self-hosted:810
    (Async: async)
    call_wrapped libWrapper-wrapper.js:507
    call_wrapped self-hosted:1521
    libWrapperInit libWrapper-api.js:803
    AsyncFunctionNext self-hosted:810
    (Async: async)
    libWrapperInit self-hosted:1409
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    AsyncFunctionNext self-hosted:810
    (Async: async)
    <anonymous> foundry.js:79675

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.3.0.
