### ISSUE TITLE
Heightened spells not working correctly

### ISSUE THREAD

**Issue by this-gavagai** [Larkinabout/fvtt-token-action-hud-pf2e#26]
Thanks so much for this phenomenal module. It has completely changed the way my table has used Foundry.

One quick bug report: Heightened spells seem not to be working correctly. If I try to cast the 2nd level of a spell that has been heightened from a level 1 base version (by clicking on the HUD button under level 2), the level one version of the spell will be cast instead.

If there is any further information or testing I can provide, please let me know!

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.3.0.

**Comment by this-gavagai** [comment]
This is great. Thank you for it!

(And apologies for the double issue post! I missed #18 somehow.)
