### ISSUE TITLE
Matching the one-line per weapon mode for PF2 Strikes 

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#29]
@Larkinabout This has been discussed multiple times and is preventing me from moving my games to the new Core. Can we talk about paid commission for options allowing to replicate the same order of buttons with a few minor improvements over the legacy? 

Please let me know (you can find me on Discord ApoApostolov#4622)

**Comment by Larkinabout** [comment]
Like this?:
![image](https://user-images.githubusercontent.com/105953297/230513861-12fa5597-9b64-4c3c-8344-9b45564c936b.png)

This is just an example done in the existing version by moving the actions around. I'll look at adding a module setting to default strikes to a single, but I can't make guarantees about when I'll get to look at it. Sorry, I'm not interested in paid commissions as I'm just doing this in my spare time and money sets expectations. Thanks for the offer though.

**Comment by apoapostolov** [comment]
This looks great for a start. Few suggestions that would improve it. 

* The first button combined with the attack should be the 0 MAP attack, not Draw/Sheathe. To not change the button type, consider separating the Draw button from the weapon icon. Otherwise, when the weapon is drawn, Sheathe becomes its own button, and the first button is always the main attack. 
* Move Drop after the MAP and Damage buttons, as priority usage of dropping weapons is very secondary to striking with it. The order of buttons, in a perfect usability case would be: [WEAPON NAME + ATTACK] -- [1XMAP] -- [2XMAP] -- [DAMAGE] -- [CRITICAL] -- [SHEATHE] -- [DROP]
* Unarmed Strike should default to the default fist icon rather than have no icon. Visually it is hard to differentiate when needed

One additional thing that would really help with the vertical alignment is to add support in core for moving the name of a section before the row of buttons right aligned, like in old Legacy TAH, as this would allow weapons to fit next to each other vertically with no loss of space (especially for fighters with 6+ weapons which is very normal experience mid-tier).

**Comment by uniwars** [comment]
"One additional thing that would really help with the vertical alignment is to add support in core for moving the name of a section before the row of buttons right aligned, like in old Legacy TAH, as this would allow weapons to fit next to each other vertically with no loss of space (especially for fighters with 6+ weapons which is very normal experience mid-tier)."
+1
I have a +2 greater striking flaming thundering glaive for example that takes 2 lines for its name creating a gap between it and the next weapon, but with legacy it's clean  :
![image](https://user-images.githubusercontent.com/65986545/230586823-c95857b0-a420-4dee-90b0-ff6f1ce0f8fa.png)
against :
![image](https://user-images.githubusercontent.com/65986545/230589092-f18af9a5-3de7-4ddf-b833-80e861d07a24.png)

**Comment by apoapostolov** [comment]
Based on my last feedback above, my proposal for weapon strikes would become.

- When weapon is sheated
- - The weapon icon is not part of the first button but is a separate button that only contains the icon. When the weapon is drawn it will become clickable and contain the First Attack value. 
- - So it looks like this [WEAPON ICON] -- [DRAW 1A]

- When weapon is drawn
- - the weapon icon is now a clickable button and contains as a text after the icon the First Attack value. Followed by separate buttons for Second Attack, Third Attack, Damage and Critical. Finally, all secondary actions such as Sheathe and Drop
- - So it looks like this [WEAPON ICON + NOMAP ATTACK] -- [1ST MAP ATTACK] -- [2ND MAP ATTACK] -- [DAMAGE] -- [CRITICAL] -- [SHEATHE] -- [DROP]

- When there is a secondary thrown/ranged attack possible with the weapon
- Create a full weapon line the same thing as the normal primary attack, but use the icon for thrown or ranged (default from PF2, and it was implemented in legacy TAH (https://github.com/Drental/fvtt-tokenactionhud/issues/307)

- Only for strikes, a better positioning for subsection titles
- Left from the start of a weapon strike line, right-alined as shown on the image below from Legacy TAH
![image](https://user-images.githubusercontent.com/4083812/230602486-158fd2ea-f071-4c2f-8a86-e41bb5c06da4.png)

**Comment by Larkinabout** [comment]
Larkinabout/fvtt-token-action-hud-core#99

**Comment by apoapostolov** [comment]
@Larkinabout No pressure from my side to deliver at all, but can you comment on my post above summarizing the changes needed to replicate the OG TAH style? Just want to know if we agree on the changes needed, or my proposal is not working for you.

**Comment by Larkinabout** [comment]
@apoapostolov, only issue is actually achieving what is proposed, not with what is proposed itself. Although it may not seem like much, each element amounts to a significant rework. It's not off the table, but I don't have a quick fix, so it's likely to stay as is until I get some inspiration or someone else solves it. Meanwhile, there are a bunch of new customisation features that should make life easier.

**Comment by Larkinabout** [comment]
Token Action HUD Pathfinder 2 1.4.3 adds images for strike groups and a module setting to hide strikes names by default.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/105953297/f9939187-b019-43b3-b44e-f2624bb7e419)

**Comment by apoapostolov** [comment]
Thank you. This is very close to perfect, not the same thing technically but if the players sheath their weapons it reverts to one line so it is close to perfect. I think it is good to stay, and thank you again for all the hard work getting here. The only pet peeve remains the Thrown category, if that can be fixed somehow #53 then I have no reasons to not migrate.

**Comment by Larkinabout** [comment]
Closing as resolved.

**Comment by Zullock** [comment]
@apoapostolov created a PR with some of those changes: https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/pull/67

**Comment by apoapostolov** [comment]
Thanks, this is looking very polished now.
