### ISSUE TITLE
Actions menu is too long

### ISSUE THREAD

**Issue by weepingminotaur** [Larkinabout/fvtt-token-action-hud-pf2e#3]
Just grabbed Token Action HUD PF2e -- delighted by it. Issue, though: the display for strikes and actions takes up a lot of space, even when using the compact style. For example, Melee and the weapons themselves being on their own lines take up too much space. And it would be great if one could toggle off the damage and critical buttons.

**Comment by Larkinabout** [comment]
Hi @weepingminotaur,

The HUD is very customisable. Try a few things to see if it helps:

**Remove Actions**
1. Unlock the HUD.
2. Right-click on a subheading to open its dialog.
3. Click the X on actions you don't want to see, such as the Damage and Critical actions.
4. Click 'Accept'.
5. Lock the HUD.

**Hide Subheadings**
1. Unlock the HUD.
2. Right-click on a subheading to open its dialog.
3. Uncheck 'Show Title' to hide the subheading. For example, hide the 'Melee' subheading to leave just the 'Thrown' subheading under each weapon.
4. Click 'Accept'.
5. Lock the HUD.

**Move Subcategories**
1.Unlock the HUD.
2. Right-click on a heading to open its dialog.
3. Click the X on a subcategory to remove it, such as 'Strikes'.
5. Click on the book icon to open the category dialog.
6. Type the name of a new category, such as 'Strikes'.
7. Drag the new category to where you want it in the order.
8. Click 'Accept'.
9. Right-click the new category to open its dialog.
10. Add a subcategory from the list, such as 'Strikes'.
11. Click 'Accept.
12. Lock the HUD.

**Sheathe Weapons**
Click the 'Sheathe' or 'Drop' action under a weapon in 'Strikes' to collapse all of the actions for that weapon. You'll most likely be doing this during normal play as you swap weapons.

**Comment by tehguitarist** [comment]
One suggestion might be to forgo the melee/ranged tag IF the weapon doesn't have both abilities. For example, a longsword doesn't have a ranged attack, so melee would be hidden. But a dagger does, so it would show both.
Alternatively, add the type in front of the buttons. Melee +10 +5 0 Damage Crit for example.

**Comment by Larkinabout** [comment]
You can hide that extra subheading using the 'Hide Subheadings' method described above. That way it remains a choice for the user. I did consider programatically hiding the titles by default, such as for 'Unarmed Attack' where 'Melee' isn't actually very useful. I have it hidden on my HUD for that reason. It was easier just to let it populate as with all other subheadings with the expectation that users would configure the HUD to their liking the first time around and then not have to worry about it.

**Comment by tehguitarist** [comment]
Understood. Looking at it, it's a per item setting, which means that players will have to do that every time they change their weapons which feels a bit rough from a UX standpoint. It's also coming from the very clean and tidy original:
<img width="681" alt="Screenshot 2023-02-13 at 8 52 56 pm" src="https://user-images.githubusercontent.com/28495826/218426874-5378dd5a-4e99-4abc-a1e6-f34d2b5cfc03.png">

To something that's a bit more verbose:
<img width="573" alt="Screenshot 2023-02-13 at 8 52 22 pm" src="https://user-images.githubusercontent.com/28495826/218426936-2dc228b0-ffc3-48f6-892c-d63c295c83d1.png">

**Comment by Larkinabout** [comment]
Yeah, the subheading to the side was awful for other reasons, but it did help shrink the overall length, not that I'm personally overly fussed with the trade off of a bit of scroll for better visible grouping.

I'll see about hiding subheadings by default for those characters with more weapons than they could possibly carry! It'll also help out the GM as they swap between monsters.

**Comment by weepingminotaur** [comment]
Thanks for the note about customizing! However, like tehguitarist I prefer the clean layout of the original TAH where the weapon names were on the left side. Anyhow, I'll investigate further.

**Comment by Larkinabout** [comment]
> Thanks for the note about customizing! However, like tehguitarist I prefer the clean layout of the original TAH where the weapon names were on the left side. Anyhow, I'll investigate further.

It may well be an option for the future, though it comes with its own headaches, making it optional per group may avoid those issues.

**Comment by apoapostolov** [comment]
Optional per section is definitely enough.

**Comment by Larkinabout** [comment]
> One suggestion might be to forgo the melee/ranged tag IF the weapon doesn't have both abilities. For example, a longsword doesn't have a ranged attack, so melee would be hidden. But a dagger does, so it would show both. Alternatively, add the type in front of the buttons. Melee +10 +5 0 Damage Crit for example.

This part was added in Token Action HUD Pathfinder 2 1.3.0.
