### ISSUE TITLE
Action menu doesn't populate

### ISSUE THREAD

**Issue by uniwars** [Larkinabout/fvtt-token-action-hud-pf2e#31]
Hi, it seems that actions menus doesn't find actions in a PC sheet if there are not in the action browser but created by a class feature or a feat :

![image](https://user-images.githubusercontent.com/65986545/230590013-c9c0f189-9ee1-40f9-9190-8ca0d22cab66.png)

**Comment by uniwars** [comment]
It's the same with the "Feats" tab

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder2 1.3.1.
