### ISSUE TITLE
Items inside a container (backpack) will not populate the Inventory section

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#32]
All items inside the backpack of a character will not appear on the Inventory tab sections, thus being unable to eat a ration or light a torch from TAH unless they are removed manually from the backpack.

**Comment by apoapostolov** [comment]
Thank you!!

**Comment by Larkinabout** [comment]
Added in Token Action HUD Pathfinder2 1.3.1.
