### ISSUE TITLE
Hidden effects show in "effects" tab

### ISSUE THREAD

**Issue by DenMesh** [Larkinabout/fvtt-token-action-hud-pf2e#33]
As the title says, if an effect on a character is hidden (unidentified), it should not be displayed in the HUD.

**Comment by Larkinabout** [comment]
Hmm, the code to fix this was ported over. I suspect the way they are structured has changed with a system update. I'll take a look later today.

**Comment by Larkinabout** [comment]
Are you logged in as the GM?

**Comment by Larkinabout** [comment]
Nevermind, they moved where the `unidentified` property is located.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.3.1.

**Comment by apoapostolov** [comment]
Thanks!!
