### ISSUE TITLE
TAH is mixing all actors actions

### ISSUE THREAD

**Issue by ariakas2008** [Larkinabout/fvtt-token-action-hud-pf2e#36]
Not sure how to describe it, but with a monster token selected this is what happens:
![image](https://user-images.githubusercontent.com/49585869/230856593-6f92e24a-93f5-4b9b-a034-827a57d6d2bb.png)
(those are PCs actions not clickable)
![image](https://user-images.githubusercontent.com/49585869/230856652-48008457-3656-4b1e-a93f-0764dfecfbd2.png)
(last ones are monster actions, clickable)
settings:
![image](https://user-images.githubusercontent.com/49585869/230856743-d8b64909-5e1b-4f6e-8047-f639dd0bcab0.png)
versions:
![image](https://user-images.githubusercontent.com/49585869/230856948-56f6c331-764f-4288-a8f6-12baf54b50c7.png)

**Comment by Larkinabout** [comment]
Hi @ariakas2008, you will need to lock your HUD when using it to the hide empty subcategories. It's working as intended, it's just messy for the GM. I'm working on moving those actor specific subcategories to the actor instead of the user in the next minor release.
