### ISSUE TITLE
Hud showing attacks for all characters on the map

### ISSUE THREAD

**Issue by fougerec** [Larkinabout/fvtt-token-action-hud-pf2e#38]
For some reason the Action tab is showing the titles for all attacks for all creatures on the map.  The cleric, Father Hul does not have mandibles...
![image](https://user-images.githubusercontent.com/84296981/235303405-afeb27f8-e62a-4150-8668-9a657aa497e3.png)

**Comment by Larkinabout** [comment]
Hi @fougerec, lock the HUD while playing. This will hide the unused groups. The next release improves this by moving actor-specific groups to the actor rather than the user.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.0.
