### ISSUE TITLE
Damage buttons in the chat cards of Strikes' primary usage don't work

### ISSUE THREAD

**Issue by alexbrault** [Larkinabout/fvtt-token-action-hud-pf2e#41]
When rolling a Strike, the Damage and Critical buttons on the chat card don't work.

This appears to be because the altUsage parameter is always passed to the `roll` function. When an altUsage is found on the chat card, the buttons' handler only looks in the altUsages array to find the Strike information. For the Strike's primary usage, that value will not be  found in the altUsages and the buttons do not work.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.1.
