### ISSUE TITLE
Hud has completely stopped working

### ISSUE THREAD

**Issue by Simyonovich** [Larkinabout/fvtt-token-action-hud-pf2e#42]
I was running the module just fine a week ago but something has changed. I've tried uninstalling all but the dependant modules and even this is not working. I've tried uninstalling and re-installing. I've tried restarting my Forge server. even cloning my world as well as creating a completely newly built world. Just refuses to work at all.
![Uploading Screenshot 2023-05-16 152321.png…]()

**Comment by Simyonovich** [comment]
I found the culprit. After clicking through every single setting, for some reason unselecting and then re-selecting the variant rule for Free Archetype

**Comment by Larkinabout** [comment]
Glad it's working again, though I'm not sure that setting would have any impact on the HUD.

Were you getting any error messages in the console while it wasn't working?

**Comment by Simyonovich** [comment]
No error messages at all. I went through and added back every singel module one by one and it still wasn't working. So I went into the settings, trying again on several tokens after each change. It was for sure the Free Archetype variant rule. the weird thing is that Hud kept working after I reselected it. Bizarre.

**Comment by Larkinabout** [comment]
Well, if it happens again, let me know and we'll see if we can unravel the mystery.
