### ISSUE TITLE
Errors in console with scaled HUD

### ISSUE THREAD

**Issue by ottyn** [Larkinabout/fvtt-token-action-hud-pf2e#45]
Foundry 10.291
PF2e 4.12.1
Token Action HUD Core 1.4.5
Token Action HUD PF2e 1.4.2

I have the HUD scale set to .75 in settings.  When using the HUD, I see the following errors in console.  HUD appears to function normally though.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/97130150/8244a6d6-aadb-4f31-b3ba-d40be63a612c)

**Comment by Larkinabout** [comment]
I don't think that's Token Action HUD as there is no reference to it in the error. 

It looks like the error has been reported about Foundry VTT v10 before: [https://discord.com/channels/170995199584108546/956306859491471420/1088537438386933892](https://discord.com/channels/170995199584108546/956306859491471420/1088537438386933892)
