### ISSUE TITLE
[Feat] Hero Action Support

### ISSUE THREAD

**Issue by cadowtin** [Larkinabout/fvtt-token-action-hud-pf2e#46]
Support to show hero actions from this module (toggleable in settings perhaps) https://foundryvtt.com/packages/pf2e-hero-actions

**Comment by Larkinabout** [comment]
https://github.com/reonZ/pf2e-hero-actions/issues/10

**Comment by Larkinabout** [comment]
Added in Token Action HUD Pathfinder 2 1.4.10.
