### ISSUE TITLE
[Feature Request] Support Modular and Versatile weapons

### ISSUE THREAD

**Issue by esheyw** [Larkinabout/fvtt-token-action-hud-pf2e#48]
Currently Versatile weapons just don't have their toggles show up at all: ![](https://i.imgur.com/ca28LA5.png)

Whereas Modular produces a button next to the weapon that does nothing useful: ![](https://i.imgur.com/tf1LbAL.png)

The Versatile stuff should be relatively simple to just mirror the buttons, since they're only changing damage type and can be represented properly by just an icon. Modular is *usually* just damage type, but there's [Switchscythe](https://2e.aonprd.com/Weapons.aspx?ID=242) complicating things, which is supposed to be able to modify traits but isn't implemented yet, so having the full text available will be important, even if it isn't currently.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Pathfinder 2 1.4.3.
