### ISSUE TITLE
PF2e Familiar Actor warning

### ISSUE THREAD

**Issue by ottyn** [Larkinabout/fvtt-token-action-hud-pf2e#49]
When selecting a familiar actor in PF2e, I see the following in the console.
Foundry 10.291
PF2e 4.12.8

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/97130150/b334f379-28e1-4718-88c9-e9b67c256ed8)

**Comment by Larkinabout** [comment]
https://github.com/foundryvtt/pf2e/issues/8137

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.8.
