### ISSUE TITLE
Inconsistency in number of buttons per row

### ISSUE THREAD

**Issue by tehguitarist** [Larkinabout/fvtt-token-action-hud-pf2e#5]
Started a new issue for cleaner tracking. 

There seems to be an inconsistency with how many buttons are on a line. Specifically on the to hit, and damage buttons. All in a row is nice, but that varies from character to character.

<img width="655" alt="Screenshot 2023-02-13 at 8 39 38 pm" src="https://user-images.githubusercontent.com/28495826/218424135-1ab92567-7e5a-451a-98bc-6a1d7ed015c9.png">

<img width="615" alt="Screenshot 2023-02-13 at 8 43 36 pm" src="https://user-images.githubusercontent.com/28495826/218424151-d74d4b03-2644-4e05-92be-73426a732daf.png">

**Comment by Larkinabout** [comment]
There used to be a css class that could be manually added to a group, but that meant the user has no choice in the matter. The 'Custom Width' effectively replaces it.

**Comment by tehguitarist** [comment]
Will this suffer from the same “settings per item”?
Sorry for these ones, just thinking of ux complaints that are bound to come up. 
I guess the trick there is the actor with more weapons ended up needing more vertical mouse movements, which as you said in the other issue, some players like to have more weapons than sense.

**Comment by Larkinabout** [comment]
The custom width setting is for the whole category. It's the same method that the non-grid layout uses, except it's not calculated based on number of actions.

**Comment by Larkinabout** [comment]
Closing as fixable via Custom Width and general improvements to the automatic resizing will happen as desired.
