### ISSUE TITLE
UX Improvement needed for thrown weapons

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#53]
For thrown weapons, the textual subcategory adds a bit of roughness to the otherwise pretty polished UI. I would love to see any solution that makes it invisible like it is for melee strikes and indicative in any other possible way. 

For example, the icon for thrown ``<img class="alt-usage-icon" src="systems/pf2e/icons/mdi/thrown.svg" title="Thrown Usage">`` can be integrated inside the MAP 0 button, or be shown before that button into the free area where the weapon icon is shown on an above row.

**Comment by Larkinabout** [comment]
Next plan is to enable icons to be used in place of images, so they can be styled more like the lock and edit icons. This'll allow the Melee and Thrown titles to be hidden and the icon to be shown instead to the left.

**Comment by apoapostolov** [comment]
This is the perfect solution, thank you very much in advance.

**Comment by Larkinabout** [comment]
Added in Token Action HUD Pathfinder 2 1.4.9.
