### ISSUE TITLE
Selecting PC Cashes HUD in FVTT v11/PF2e v5.0.0-beta1

### ISSUE THREAD

**Issue by Forny008** [Larkinabout/fvtt-token-action-hud-pf2e#55]
In FVTT v11/PF2e v5.0.0-beta1 selecting a PC causes the Action HUD to crash, and it cannot be used again until refreshing the page. This behavior happens every time for both GMs and Players. I tested for module incompatibility in a new world with only Action HUD enabled and the crash still occurred. 

[Debug log beginning with PC select](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/files/11730697/localhost-1686631069378.log)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.7.
