### ISSUE TITLE
[BUG] PF2 setup has Attacks section that is improperly set

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#56]
In PF2 setup there's Attacks section that never renders because it has content "Subcategory: Attacks" and PF2 does not have content for that section. The proper section hat should be there is "Subcategory:Strikes" and maybe the section should be called Strikes. 

In fact, to make it work as it was in Legacy TAH, the best way would be:
- Rename Attacks into Strikes (to use PF2 naming)
- Put both Subcategory: Toggles (on the bottom) and Subcategory: Strikes in it (on the top)
- Remove Subctategory: Toggles and Subcategory: Strikes from Actions

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/4083812/f0135009-90be-4b9c-a471-e0eca31b549b)

**Comment by Larkinabout** [comment]
The Attacks group is specifically for familiar attacks.

You might need to reset your HUD as the default layout now has a separate Strikes group at the top level.

**Comment by Larkinabout** [comment]
Closing as answered.
