### ISSUE TITLE
Weapon Icon and title remain after being deleted

### ISSUE THREAD

**Issue by Caboosee** [Larkinabout/fvtt-token-action-hud-pf2e#57]
When I add the throwing knife +1 it remains on the strikes hotbar no matter what I try and do. I've refreshed, tried on different characters and I'm still unsure.

Thank you
![Issue](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/136930529/45c6f188-423c-44f4-bcc9-031079980ffc)

**Comment by Larkinabout** [comment]
I don't seem to be able to reproduce this. Can you please try unlocking the HUD, right-click on the Strikes title and then manually remove that strike group from the list. If that doesn't work, please export the actor and attach it to this issue.
