### ISSUE TITLE
Selecting a Hazard Token breaks the token action hud

### ISSUE THREAD

**Issue by dmpunks** [Larkinabout/fvtt-token-action-hud-pf2e#58]
Steps to reproduce:
1. Select a hazard token - no HUD will pop out
2. Now select any PC or NPC token.

Expected Result: HUD will appear
Actual Result: Token HUD no longer functions until a refresh is done

Console:
![tokenhudconsoleerror](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/1963509/7a9f98bb-ec3d-41cb-bf48-ae107cc4783e)

FoundryVTT version: 11 Build 302
Pathfinder 5.0.2
Active Modules: 
- Token Action HUD Core v. 1.4.9
- Token Action HUD Pathfinder 2e v. 1.4.8

Notes:
1. I think there should at least be a HUD labeled "Utility" when selecting Hazards. IIRC that was the behavior in Classic and Foundry 10.
2. Currently, selecting Loot NPC tokens behave correctly, providing an empty "Utility" HUD.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.9.

**Comment by dmpunks** [comment]
Awesome, thanks!
