### ISSUE TITLE
NPC's don't have some toggles 

### ISSUE THREAD

**Issue by heyzoms** [Larkinabout/fvtt-token-action-hud-pf2e#59]
I've checked the **Burglar**, and **Ruffian** both don't have the toggle feature as players do, to enable their features for extra damage if a target if flat-footed. 
![image_2023-06-22_143322939](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/109550182/af9bda6d-3a7b-4ad4-a755-33ce5252cbf1)

I'm I doing something wrong? or is their just not implemented yet?

**Comment by Larkinabout** [comment]
The HUD only adds toggles that exist on the actor. It doesn't look like the Ruffian actor has any toggles as far as I can see.
