### ISSUE TITLE
[BUG] Icons display in strikes even with option off

### ISSUE THREAD

**Issue by Zullock** [Larkinabout/fvtt-token-action-hud-pf2e#61]
If the option "Icon Display" from Token Action HUD Core is off, the icon for the weapons still show up in the strikes.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/29728598/358b0650-6d19-4724-8497-34246325f31b)

**Comment by Larkinabout** [comment]
That setting only works on actions, not groups, but I can see a need to allow the group images to be hidden for strikes by default.

**Comment by Larkinabout** [comment]
Added the 'Show Strike Images' module setting in Token Action HUD Pathfinder 2 1.4.9.
