### ISSUE TITLE
[Enhancement] Sort Conditions Alphabetically 

### ISSUE THREAD

**Issue by git-kor-av** [Larkinabout/fvtt-token-action-hud-pf2e#63]
It's great to have the Conditions listed under the Effects tab, however I'm wondering if they could be sorted alphabetically.  Alternatively, it would be helpful to have them sorted by Alphabetically, but also by grouping them.  Meaning those affecting attitude could be grouped together, as well as those effecting whether or not someone is visible or not.

**Comment by Larkinabout** [comment]
Hi @git-kor-av, you can already sort actions alphabetically using the dialog. See [Sort Actions Alphabetically](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/How-to-Use-Token-Action-HUD#sort-actions-alphabetically). You can also drag actions into a different order using the same dialog, you'll just need to make sure to untick the 'Sort Actions' checkbox.
