### ISSUE TITLE
[Question/Issue] Hiding titles doesn't seem to work. Not sure if bug or stupidity

### ISSUE THREAD

**Issue by ILikeCoolThings** [Larkinabout/fvtt-token-action-hud-pf2e#65]
Hi there.

I am having trouble hiding the titles of the strikes. None of the options, module setting or individual group, seem to help. I have tried this with only the base modules enabled, as well as uninstalling/resetting both the core and pf2e modules. No errors in the console exist.

This is what I am constantly seeing without the ability to turn off the titles of each item.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/54457140/856ef982-2ff6-4cf9-924e-a7d8a9a83dc5)

Any help would be appreciated.

**Comment by Larkinabout** [comment]
Hi @ILikeCoolThings, you just need to lock the HUD as all titles are shown while the HUD is unlocked to enable them to be edited. See the first video here: [How to Use Token Action HUD](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/How-to-Use-Token-Action-HUD).
