### ISSUE TITLE
Perception error in PF2E 5.2.0

### ISSUE THREAD

**Issue by ottyn** [Larkinabout/fvtt-token-action-hud-pf2e#70]
Foundry: 11.306
PF2E: 5.2.0
TAH Core: 1.4.16
TAH PF2e: 1.4.11

New console error with the updated system.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/97130150/be04bcf3-dc3c-4b36-b200-6cf3d2833e9f)

**Comment by chrisryan10** [comment]
Looking at the console, it looks like `CONFIG.PF2E.attributes.perception` doesn't exist any more.  There's a `CONFIG.PF2E.perception` but it's not of the correct data structure expected.

**Comment by Larkinabout** [comment]
Looks like a temporary fix is coming in the next release of the PF2e system, but I'll try to release a fix for Token Action HUD this evening.

**Comment by DoritoBob** [comment]
I am getting the same error, the perfection issue seems to be knocking out a few other modules as well, such as Monk Token Bar

**Comment by ottyn** [comment]
Can confirm that PF2e 5.2.1 has resolved the issue with TAH and Tokenbar.  They are now showing the following warning in console for depreciation if it helps to permanently fix the issue.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/97130150/bb28a896-9eea-49e3-95c7-b3a460fa57e0)

**Comment by DoritoBob** [comment]
Can confirm, Token Action HUD and Monks Token Bar are working now

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.12.
