### ISSUE TITLE
Secondary and tertiary strikes show NaN after PF2E system update 5.2.1

### ISSUE THREAD

**Issue by Silvertower** [Larkinabout/fvtt-token-action-hud-pf2e#72]
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/8496016/ba2f30f5-fc99-4ec6-9da4-a34866d7cf3d)

This appears to be caused by the following change:

* (In3luki) Show adjusted modifier on strike MAP buttons

**Comment by uniwars** [comment]
Getting the same issue

**Comment by Larkinabout** [comment]
Until I can release a fix, I think disabling the 'Calculate Attack Penalty' module setting may fix it as it'll use the default label and those now have the calculation included.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.12.
