### ISSUE TITLE
Bludgeoning icon for versatile weapons is blank

### ISSUE THREAD

**Issue by Silvertower** [Larkinabout/fvtt-token-action-hud-pf2e#73]
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/8496016/52c4f15e-3e2e-42c8-ad73-e574d05c2c7f)

**Comment by Silvertower** [comment]
Tested with a fresh world with Token Action Hud PF2E 1.4.12 on Foundry v11 build 306 and PF2E 5.2.1 system.

**Comment by Silvertower** [comment]
Looks like line 1794 is missing the 'hammer' option.

https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/blob/68b1c111d155a4da4752bc0308bcbf5858614f52/scripts/action-handler.js#L1794

**Comment by Silvertower** [comment]
Can confirm that updating the scripts/token-action-hud-pf2e.min.js file as follows resolves the issue:

Replace:

`s={1:"<span style='font-family: \"Pathfinder2eActions\"; font-size: var(--font-size-20);'>A</span>",2:"<span style='font-family: \"Pathfinder2eActions\"; font-size: var(--font-size-20);'>R</span>","bow-arrow":"fa-solid fa-bow-arrow fa-fw",axe:"fa-solid fa-axe fa-fw",hammer:"fa-solid fa-hammer fa-fw"}`

With:

`s={1:"<span style='font-family: \"Pathfinder2eActions\"; font-size: var(--font-size-20);'>A</span>",2:"<span style='font-family: \"Pathfinder2eActions\"; font-size: var(--font-size-20);'>R</span>","bow-arrow":"fa-solid fa-bow-arrow fa-fw",axe:"fa-solid fa-axe fa-fw",hammer:"fa-solid fa-hammer fa-fw"}`

And replace:

`#M(e,t=""){return["bow-arrow","axe"].includes(e)`

With:

`#M(e,t=""){return["bow-arrow","axe","hammer"].includes(e)`

**Comment by Larkinabout** [comment]
On holiday for a few days, but will sort when I get back.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.13.
