### ISSUE TITLE
[Feature request] - show reach of strikes

### ISSUE THREAD

**Issue by Maelorn09** [Larkinabout/fvtt-token-action-hud-pf2e#74]
Hi, the request is self-explanatory. If possible, please consider adding Reach/Range to the strike description, so there is no need to open NPC sheet to check this. 
Below is the example of Cloud Giant strikes, all of them have different ranges. It would be awesome to see them during an encounter because it directly changes the targeting routine.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/114569560/6238a57b-9b61-4d7a-96b6-1d194cd714e6)

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/114569560/12bdfd65-13b0-459c-9670-9d63e9cbb209)

**Comment by Larkinabout** [comment]
Are they shown on the tooltip when you hover over the strike icon/image?

**Comment by Maelorn09** [comment]
> Are they shown on the tooltip when you hover over the strike icon/image?

Yes, but the tooltop for me is unusable since once it appears for 1 entry after 2 sec pause - then it appears for other entries instantly and some of them block the HUD so I can't see other entries, so I turn them off. 
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/114569560/e0a03307-ab55-4185-940b-6126a9421e36)

**Comment by Larkinabout** [comment]
I'm using the built-in Foundry VTT tooltips and I've raised an issue here: https://github.com/foundryvtt/foundryvtt/issues/9662 to see if it's possible to configure tooltip display where there's a lot of content.

I'll have a look to see if it's possible to override the behaviour of showing additional tooltips immediately as it's a fairly undesirable feature in this instance. That should help avoid the tooltips showing too often and getting in the way when you don't intend to view them. I imagine only showing a tooltip after a slightly longer delay will also help.

I'd rather solve the request this way, then put the info in the strike name.

**Comment by Silvertower** [comment]
Added in 1.5.5 via the Show Strike Traits option. This will show range or range increment, or reach, etc. based on the traits of the weapon.
