### ISSUE TITLE
Ctrl+Clicking Perception rolls secret GM check instead of blind GM 

### ISSUE THREAD

**Issue by ttocs240** [Larkinabout/fvtt-token-action-hud-pf2e#75]
While using the attributes tab to roll Perception, when a PC uses the standard PF2e Ctrl+Click functionality, it produces a "secret GM roll" (one where the player and the GM can see the result). It should produce a "blind GM roll" (where only the GM sees the result). This error does not occur for the skills tab.

**Comment by Larkinabout** [comment]
What versions of the modules are you on?

**Comment by ttocs240** [comment]
This is currently happening on 1.4.12 (PF2e) and 1.4.16 (Core).

**Comment by Larkinabout** [comment]
> This is currently happening on 1.4.12 (TAH PF2e) and 1.4.16 (TAH Core).

Thanks for the update.

**Comment by Larkinabout** [comment]
Is there a module or setting that changes the default behaviour as when I CTRL-Click on the character sheet it produces a private GM roll for initiative, perception and saves?

![token-action-hud-pathfinder-2-ctrl-click](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/105953297/33a5238c-787f-4fd1-b504-fe5a9e166f75)

**Comment by Larkinabout** [comment]
Ah wait. It might be because I'm logged as GM. I'll test as player.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Pathfinder 2 1.4.13.
