### ISSUE TITLE
[Bug] Hero Actions Missing Description in Tooltip

### ISSUE THREAD

**Issue by ChasarooniZ** [Larkinabout/fvtt-token-action-hud-pf2e#77]
Hero Actions only show their name, not their description in the tooltip
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/79132112/ed7d0d76-ce9e-448c-a7a4-7b1e8b9535fb)

**Comment by Larkinabout** [comment]
Added in Token Action HUD Pathfinder 2 1.4.14.
