### ISSUE TITLE
[BUG] getIndex Error

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-token-action-hud-pf2e#78]
Further information, when selecting a token, I observe the following in my Chrome browser console log (115.0.5790.110 (Official Build) (64-bit)):
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/140914138/b5c91791-8c05-4316-a820-e16270713c27)
Hope that helps.
Thanks in advance.

_Originally posted by @Grafvollud666 in https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/69#issuecomment-1656827501_

**Comment by Larkinabout** [comment]
As I'm not able to reproduce this error, it may be specific to your setup.

Does the error still occur with all other  modules disabled?
Does it occur on a fresh world created in V11?
Have you tried clearing the cache?

**Comment by Grafvollud666** [comment]
Thank you [Larkinabout](https://github.com/Larkinabout) for your response :)

Looks like the issue may be isolated to Forge-VTT. Know that during my previous testing I did try disabling all modules except for Token HUD and the hud did not appear.

I also observed that Foundry/PF2e Compendiums were not working as well. Know that I'm running three PF2e games with Forge-VTT. I was advised to a) shutdown all worlds, b) uninstall/reinstall PF2e, c) startup worlds to resolve the Compendiums issue. I've now discovered that Forge-VTT has a known concerns with v11 & Compendiums when running multiple worlds. If you only have one world active, the Compendium Packs are accessible. Until resolved I can only have one World/Server active at a time. Hopefully this will be resolved quickly :)

After doing this I realized that Token HUD now works.
This also seems to be related to the multiple worlds issue for Forge-VTT as well.
E.g. Start world https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/1 = Token HUD ok, Compendium = ok.
Start world https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/2 (world https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/1 still active) and Token HUD & Compendium do not function for world https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/2. World https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/issues/1 is ok.

In summary, ignore my situation for the time being. I have a workaround. Be aware of this multiple worlds active at once issue for Forge-VTT that seems to affect at least a few modules/features.
Hope this helps.
Thank you again, much appreciated :)

**Comment by Grafvollud666** [comment]
Also, clearing the browser cache did not help.
