### ISSUE TITLE
Attacks Disappearing from HUD in PF2e

### ISSUE THREAD

**Issue by computerpro82** [Larkinabout/fvtt-token-action-hud-pf2e#79]
In my games the last two weeks, we have had issues with attacks disappearing from the HUD. I am running the latest version of the HUD. During the first instance, I was running on Foundry V10 and I was having this issue as the GM. During the session on 7/29, one of the players had the issue.. Between the sessions, I had upgraded to V11. I am running in The Forge. My previous version had been V10 Build 303. I am now on V11 Build 306.
The issue is intermittent, and I have not been able to reproduce it.

**Comment by Larkinabout** [comment]
There's been a few other reports of the same, although I've not yet been able to reproduce. If it happens again and you're able to have a look at the browser console, capture any errors that might be there as that'll help diagnose the issue.

**Comment by computerpro82** [comment]
Do you have specific steps for capturing what you need? I am pretty
computer savvy, but I am not a developer.
--
Eric S. Parker
719-481-0786(h)
719-339-6509(c)
Quote from Babylon 5, US Television show, originally aired 1993-1998"Mr.
Garibaldi, there're days I'm very glad I don't have to think the way you
do."
*Ivanova*, *And the Sky Full of Stars*

“There is a cult of ignorance in the United States, and there has always
been. The strain of anti-intellectualism has been a constant thread winding
its way through our political and cultural life, nurtured by the false
notion that democracy means that 'my ignorance is just as good as your
knowledge.”
― Isaac Asimov

**Comment by lammonaaf** [comment]
I'm facing the same issue: I do not see anything special in console, but what I've noticed is that if I unlock HUD (via lock icon), the attack section appears, containing no entries.

**Comment by jnokes10** [comment]
bundle.min.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at NpcActionHandlerPf2e._addTogglesCategories (bundle.min.js:1:142167)
    at NpcActionHandlerPf2e._getStrikesListNpc (bundle.min.js:1:142019)
    at NpcActionHandlerPf2e.buildActionList (bundle.min.js:1:140619)
    at ActionHandlerPf2e.doBuildActionList (bundle.min.js:1:143869)
    at ActionHandlerPf2e.buildActionList (bundle.min.js:1:41363)
    at TokenActionHUD.updateHud (bundle.min.js:1:27079)
    
    I get this error in the consul.  I am using Chrome as my browser.
    I hope this helps.

**Comment by Larkinabout** [comment]
> Do you have specific steps for capturing what you need? 

You can open the browser console by pressing F12. Usually at the bottom of the window that pops up is the console log showing everything that has happened. If you scroll through the log, you may see errors coloured red. Take a screenshot of these.

**Comment by Larkinabout** [comment]
> I'm facing the same issue: I do not see anything special in console, but what I've noticed is that if I unlock HUD (via lock icon), the attack section appears, containing no entries. Also, re-selecting the token helps.

The Attack section is specifically for familiar and will not show anything for characters. When you unlock the HUD is shows all the sections, even ones that are usually hidden when the HUD is locked.

Is it the Strikes section that disappears?

**Comment by lammonaaf** [comment]
Yes, I misremembered the actual name of the section, sorry. To be precise, both Strikes and Spells sections disappear at the same time, seemingly at random moments. That also applies to monster tokens too.

**Comment by Larkinabout** [comment]
> Yes, I misremembered the actual name of the section, sorry. To be precise, both Strikes and Spells sections disappear at the same time, seemingly at random moments. That also applies to monster tokens too.

It sounds like the HUD might be detecting multiple tokens. Can you see the character name at the top of the HUD? Does it say 'Multiple'?

Put this code into a script macro and If it happens again, execute the macro, save the file and upload it to this issue: `saveDataToFile(JSON.stringify(game.tokenActionHud.hud, null, 2), 'text/json', 'token-action-hud.json')`

**Comment by lammonaaf** [comment]
Okay, here it is. I also have a vague feeling that it may somehow relate to interaction with Monk's combat details. I'm also attaching the normal state after re-selection token, for comparison.

[reproduced.zip](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/files/12235830/reproduced.zip)
[normal.zip](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/files/12235831/normal.zip)

**Comment by lammonaaf** [comment]
> I also have a vague feeling that it may somehow relate to interaction with Monk's combat details.

Cannot confirm. I disabled all monk's modules, and the issue is still here: It somewhat reliably triggers at the start of a combat encounter and when switching next combatant from combat tracker.

**Comment by computerpro82** [comment]
As a point of reference, I don't have any of monk's modules installed, much
lees active/enabled. I will try to reproduce in a more realistic combat
encounter using the combat tracker when I can.
--
Eric S. Parker
719-481-0786(h)
719-339-6509(c)
Quote from Babylon 5, US Television show, originally aired 1993-1998"Mr.
Garibaldi, there're days I'm very glad I don't have to think the way you
do."
*Ivanova*, *And the Sky Full of Stars*

“There is a cult of ignorance in the United States, and there has always
been. The strain of anti-intellectualism has been a constant thread winding
its way through our political and cultural life, nurtured by the false
notion that democracy means that 'my ignorance is just as good as your
knowledge.”
― Isaac Asimov

**Comment by lammonaaf** [comment]
Can confirm that after the last update of the core module I'm no longer facing this issue.

**Comment by Larkinabout** [comment]
> Can confirm that after the last update of the core module I'm no longer facing this issue.

Thanks for the update.
