### ISSUE TITLE
Adding +X modifier values to Skills, Saves and Lores (optional if needed)

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#8]
Playing with Attributes and Skills I noticed that while Perception has such a value hint that helps reduce need to check with Character Sheet, the other options do not have it. 

Would be great if options that are not items that can be renamed, edited or lost such as Skills and Attributes could have optional display or not of their metadata, in the case of Skills, Saves and Lores this metadata would be their value. 

In addition, the value could use the colors for Trained, Expert, Master and Legendary. I have posted below the hex codes:

- Untrained `#424242`
- Trained `#171f67`
- Expert: `#3c005e`
- Master: `#664400`
- Legendary: `#5e0000`

![image](https://user-images.githubusercontent.com/4083812/218452317-183057ea-bf6c-4acd-9d6e-3c939b649d75.png)

**Comment by Larkinabout** [comment]
![image](https://user-images.githubusercontent.com/105953297/219992224-47837bae-6d2a-400c-8ee3-90c54b73cf18.png)
![image](https://user-images.githubusercontent.com/105953297/219992228-c7c34525-f31e-43ad-b6ee-ce01058a0868.png)
![image](https://user-images.githubusercontent.com/105953297/219992232-4a60c347-c9ec-4b44-9bfd-7e3d25cfd40f.png)

**Comment by Larkinabout** [comment]
Added in Token Action HUD Pathfinder 2 1.3.0.
