### ISSUE TITLE
Strike bonuses displaying incorrectly with Automatic Bonus Progression

### ISSUE THREAD

**Issue by EitherOrlok** [Larkinabout/fvtt-token-action-hud-pf2e#80]
**Describe the bug**
Strike bonuses are displaying in the wrong order.  Anything 10 or higher is sorted in ascending order, followed by anything 9 or lower in ascending order. 

![order](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/116834318/2cc52aa6-8d04-4c39-b25a-84a0ddd72958)

This applies to all characters created in a game with the Automatic Bonus Progression variant rule active.  Dragging a character from Actors that was created in a world that does not use that variant rule displays their strike bonuses correctly.

Disabling the Automatic Bonus Progression variant rule does not cause the strike bonuses to revert to their descending ordering.

**Steps to reproduce**
Loaded a PF2 game with no mods active.  Enabled Action Hud Core, Action Hud for PF2, and SocketLib.

**Versions:**
- Token Action HUD Core: 1.4.18
- Token Action HUD System: PF2e 1.4.13
- System: PF2e
- Foundry VTT: v11 
- Browser: MS Edge 115.0.1901.203, 64-bit / Firefox 116.0.3, 64-bit

**Additional context**
socketlib 1.0.13
Games are hosted on Forge

**Comment by EitherOrlok** [comment]
UPDATE:  Copying the characters and placing the copies in a scene reverts the bug and strike bonuses display correctly.

**Comment by Larkinabout** [comment]
It looks like you may have the Sort Actions Alphabetically option enabled on either those groups or in Token Action HUD Core module setting. If you disable those settings and then reset the layout it should reset to the default unsorted order.

**Comment by EitherOrlok** [comment]
I tried that and they didn't fix the values  It's not the actions names that need resorting, but the first/second/third action strike bonuses.

**Comment by Larkinabout** [comment]
If you don't have the Sort Actions Alphabetically option enabled anywhere then try removing and then re-adding the Strikes group on the HUD.

**Comment by EitherOrlok** [comment]
That created a nested set of strikes that looked like this.

Unarmed Attack >
  Unarmed Attack >
    Unarmed Attack>  
    
Removing weapons and then putting them back into the characters' inventories fixed the issue in those cases, but there were no icons and no names for the strikes, only the buttons for attacks and damage.

And I could not find a way to remove and replace an unarmed strike that didn't give me that nested strike display.

As I posted in the update above, making a copy of the character fixes everything, so at least that's a workaround for this weird set of glitches.
