### ISSUE TITLE
Attack Icons/Titels for NPCs [Feature Request]

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [Larkinabout/fvtt-token-action-hud-pf2e#81]
When you controll heros you have nice icons to show you which button is for which attack. When you controll a NPC you just get the same icon for all attacks making it impossible to distiguish between attack when the NPC has more than two. (I know you can hover over the attacks to get the name shown but it takes time and it annoying
I see two possible solutions, one easy and one hard one.
The easy: For all attacks that don't have a unique icon, put the name of it over it or in the icons place. The Icon for many could just be a the initials like "SB" for Shortbow, "Wh" for Whip, ...
The hard one: Find generic Icons for all attacks. Most attacks are already named after weapons like "Shortsword". So just take the shortsword icon and put it there. Others might not be so straight forward like attacks with natural weapons ("Jaws, Claw, Tail, Horn, ..") and some are even kind of impossible like "Fleshy Slap" and "Bone Shard" on the Shanrigol Heap. For those one you could still use method one but most attacks should be straight forward

I hope this is possible for you

**Comment by Larkinabout** [comment]
Ideally, the system would handle unique icons for each strike. The hard one you've suggested probably isn't viable but I can look at doing something like the easy option.

As an aside, you can show the names of strikes by default enabling the 'Show Strike Names' module setting.

**Comment by Fabrice-Schoeneberger** [comment]
Oh yea. The 'Show Strike Names' is basicly what I wanted. Wooops.
Well Icons still wouldn't be bad but whatever is possible/viable

**Comment by Silvertower** [comment]
Closed as out of scope. Show Strike Names is the best option to accomplish this.
