### ISSUE TITLE
Perception on the skill tab [bug] or [mini feature request]

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [Larkinabout/fvtt-token-action-hud-pf2e#82]
Every skill is in the skill tab, except for the preception skill. There is no way to perform a perception check for either a PC or NPC from the Action Hud. The preception entry on the Attribute tab only rolls for initative or does nothing. I don't know if this in intentional but I think it should be there. an easy way to roll for preception. I hope that one isn't that hard to add

**Comment by Larkinabout** [comment]
Hi @Fabrice-Schoeneberger, there should be a separate group for the Perception Check in the Attributes group by default. This is as well as the Perception action for initiative. Perception doesn't appear in the Skills group by default as it's not structured that way on the character sheet

If the perception check action isn't doing anything on the HUD, then a system update may have changed how it functions. I'm not going to be back at my.computer for a while, but I'll check it when I can.

**Comment by Fabrice-Schoeneberger** [comment]
Yea I've seen the extra perception button, but it doesn't do anything for me.

**Comment by Zatorg** [comment]
Having the same issue, it says `t.rollAttribute is not a function`.

**Comment by Larkinabout** [comment]
Fixed in 1.4.17.
