### ISSUE TITLE
Effects not in alphabetical order (bug)

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [Larkinabout/fvtt-token-action-hud-pf2e#85]
The conditions under the effects tab are semingly randomly placed, making it very hard to find the one you are searching for.
It would help if they would be presented in alphabetical order, like everywhere else

**Comment by Larkinabout** [comment]
By default actions are sorted in the same order as their source. If you want to sort them alphabetically, unlock the HUD, right-click the group title and tick the Sort Actions Alphabetically option. Don't forget to lock the HUD again afterwards.

**Comment by Bryan-Legend** [comment]
This is way to difficult to find. It should default to sorted! Bad usability otherwise.

**Comment by Bryan-Legend** [comment]
<img width="341" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/920120/9b8aee03-3b68-41f4-bb0b-681714e4d3e3">

**Comment by Silvertower** [comment]
This issue was closed with a resolution. Not a bug.

**Comment by Bryan-Legend** [comment]
It's incredibly bad default usability. It's a bug and should be re-opened and fixed.

NOBODY WANTS TO USE THIS:
<img width="341" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/920120/3bf1e87a-f770-43d3-938d-e4180f987736">

**Comment by Silvertower** [comment]
Feel free to fork the repository and implement this feature.
