### ISSUE TITLE
PF2 5.4.0 - Nested "Use" functions not supported

### ISSUE THREAD

**Issue by pauleszczynski** [Larkinabout/fvtt-token-action-hud-pf2e#86]
Investigator's "Devise a Strategem": 'Use' nested function was added in PF2E 5.4.0

The 'Use' function works from the character sheet.

If it's selected from Token Action HUD, it sends the Action but not "Use" nested function to chat (mirroring behaviour in previous versions)

Similar behaviour for Magus' "Arcane Cascade", and likely all 'nested Use' functions from 5.4.0

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/4505709/c616fbfc-9410-403b-8a5d-7da36a57e7d5)

**Comment by Larkinabout** [comment]
Until there is an accessible `item.useAction` function or similar, this'll be too cumbersome to maintain long term as it requires duplicating system code. I'll put this as blocked until the situation changes.

**Comment by Larkinabout** [comment]
Added in 1.5.1.
