### ISSUE TITLE
Enabling "Sort Actions alphabetically" Sorts numbers for attack mods (bug)

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [Larkinabout/fvtt-token-action-hud-pf2e#87]
I only see one option to enable "Sort Actions alphabetically" and it's global for every tab. This also sorts the numbers for attack mods
![Screenshot 2023-08-31 161544](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/64808681/cc6c7f8f-9091-4477-a9d8-be642237e356)
I don't see an option to trigger that behavior for individual tabs. Global is I think fine but I also think that it should exclude the attack buttons

**Comment by Larkinabout** [comment]
For sorting inidividual groups, check out: https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/How-to-Use-Token-Action-HUD#sort-actions-alphabetically
