### ISSUE TITLE
PF2e 5.4.x Elemental blast not appearing in the HUD

### ISSUE THREAD

**Issue by uniwars** [Larkinabout/fvtt-token-action-hud-pf2e#89]
Hi, it seems that when using "channel elements" to activate elemental blast they don't appear in the token action HUD

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/65986545/b5511d9b-0f6d-4c74-add1-db0c9b7c7ec0)

**Comment by XtremelyBadProgrammer** [comment]
Hi, just wanted to add that this is not just Elemental Blast; it appears that the Pathfinder Game System implementation team have made the Kineticist work fundamentally differently than other classes.
The first is that many of their actions have these small "Use" buttons under them that send a different action type to the chat box.
<img width="322" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/141167463/d81d38bd-d4b3-488c-af45-88117a57f3e3">
<img width="208" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/141167463/4032845e-822a-47ae-9536-7f98050e948c">
As you can see this is not the same as just posting the Action "Channel Elements" to the chat, there's additional functionality.
The second is that when the actor is effected by Kinetic Aura, the Elemental Blast Attacks become active as in the screenshot above. However, the Token Action HUD is only picking up the Toggle and placing it on the action bar (also shown in the screenshot in the OP).
The third problem is that these Elemental Blasts are further modified by other feats that the Kineticist can pick, and it gets pretty gnarly. Here's a Kineticist with an Elemental Blast that is affected by Weapon Infusion and Versatile Blasts, which allow the actor to pick from various damage types as well as add various riders to the attack:
<img width="374" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/141167463/5e3820fa-8bd3-41c2-9236-423ffdeea097">
Token Action HUD does pick up the Melee and Ranged toggles but it does not display the drop downs and clicking on them does nothing.
I hope this additional info helps in some way.

**Comment by uniwars** [comment]
[fvtt-Actor-test-Ju7WB0j9DPyIIjgm.zip](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/files/12609106/fvtt-Actor-test-Ju7WB0j9DPyIIjgm.zip)
here a test actor with channel element active

elemental blast (fire for this actor) are populated in the actor sheet but not in the token HUD

**Comment by Larkinabout** [comment]
Added support for Elemental Blasts in 1.4.16. The 'use' functionality is still blocked for the time being.
