### ISSUE TITLE
Calculated Attack Penalty Is not ordered correctly

### ISSUE THREAD

**Issue by Celleron** [Larkinabout/fvtt-token-action-hud-pf2e#91]
![TokenActionHUDproblem](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/10387718/87e0e68a-41e3-417c-8d0a-3945bfc242d6)

As shown in the attachment, the Token Action HUD multiple attack penalty isn't ordered correctly. It usually shows 0, -5, -10 from left to right, but now it's not ordered properly.

**Comment by DoritoBob** [comment]
I am having the same issue still showing up for both creatures and player characters.  Does cause some confusion especially when the creature or player character has every different attack options.

![Screenshot 2023-10-10 at 6 20 25 PM](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/140255307/aad3140d-1a91-4ef2-bd6e-8291b888d307)

![Screenshot 2023-10-10 at 6 20 45 PM](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/140255307/927176bf-a99a-4ccf-841f-e04f39310b36)

![Screenshot 2023-10-10 at 6 21 29 PM](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/140255307/c0253a07-5553-427f-b2b2-987fb3d82077)

**Comment by Larkinabout** [comment]
Make sure to disable 'Sort Actions Alphabetically' in both the Token Action HUD Core module setting and the group's dialog. When done, reset the actions within the groups by unlocking the HUD, clicking the cog, and clicking 'Reset Actions within Groups'.
