### ISSUE TITLE
[Bug] Can't Toggle off Toggle a with multiple options any more

### ISSUE THREAD

**Issue by ChasarooniZ** [Larkinabout/fvtt-token-action-hud-pf2e#92]
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/79132112/4ebb2363-639f-4e97-9d41-b6a6875cb8e3)
As example can't toggle this on and off can only switch type.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/79132112/6d0608ed-4f04-4d76-b5d1-50a00918d44d)

**Comment by Larkinabout** [comment]
Just when I think it can't possibly get any more convoluted! I'll maybe look at just doing it so clicking the active type also toggles it off.

**Comment by Larkinabout** [comment]
Fixed in 1.4.17.
