### ISSUE TITLE
Latest Token Action HUD PF2e not compatible with 5.2.3

### ISSUE THREAD

**Issue by markflo765** [Larkinabout/fvtt-token-action-hud-pf2e#93]
Just wanted to give a heads up that when I updated TA HUD Pf2e on my Foundry (v11, 313. PF2e 5.2.3) the module started throwing errors and would not work. Updated to latest PF2e (did not want to do so yet, but HUD is important!) and all working again.

**Comment by Larkinabout** [comment]
Should be fixed in 1.5.1 although I haven't tested it.
