### ISSUE TITLE
[Feature request] - Make all Auxiliary actions to be after strike numbers

### ISSUE THREAD

**Issue by VicenarySolid** [Larkinabout/fvtt-token-action-hud-pf2e#94]
Is this possible to made a custom option for all Auxiliary actions to be after strike actions, just like it was on old versions?
I have figured out a way to move them per each weapon separately , but it is really time consuming to do it for all of them. Very thank for your work!

**Comment by Silvertower** [comment]
@VicenarySolid Can you give an example of what you mean by this, such as more descriptive text, or ideally, a screenshot?

**Comment by VicenarySolid** [comment]
> @VicenarySolid Can you give an example of what you mean by this, such as more descriptive text, or ideally, a screenshot?

Sure! This is where auxiliary actions rests now:
![Screenshot 2024-01-13 141404](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/22013052/ff383c2e-b039-4643-a6e5-060b4e0843fd)

This is where it was in older versions:
![Screenshot 2024-01-13 141328](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/22013052/f286e22e-a5d2-46eb-a664-77688b521482)

I can do that manually now, but it is not working good. You need to manually do this for every weapon and the interface to do that is pretty clunky. It would be cool to have an option to have Strikes always first and Aux actions to be the last actions in a row

**Comment by Larkinabout** [comment]
Added in 1.5.5.
