### ISSUE TITLE
Images Not Showing Up for Strike Actions in HUD

### ISSUE THREAD

**Issue by Kay9Cop** [Larkinabout/fvtt-token-action-hud-pf2e#96]
Upgraded to PF2e version 5.8.2 and Token Action HUD Core and PF2e 1.5.1.  Show Strike Names and Show Strike Images are checked globally but don't seem to do anything whether turned on or off.  A fighter actor and a cleric actor have images that show up next to Strike actions in the HUD, but a barbarian, bard, and wizard don't have images.  Confirmed with one other GM that he is having the same issue.  I was able to add images manually for each strike for the actors that aren't populating automatically.

**Comment by Kay9Cop** [comment]
Screenshot with images as nomal:

![Images](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/149881571/6819c0e5-9e5e-4652-a08e-1ca916a2dc2c)

Screenshot with no images:

![No Images](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/149881571/79184848-0853-4a96-8ff2-ece8f1ef00ad)

Screenshot with images added manually:

![Manually Added Images](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/149881571/88c0bb51-9cdc-440e-8a0b-629cf940a2c2)

**Comment by Kay9Cop** [comment]
I saw on the Foundry VTT PF2e Discord that a user recommended using "Reset Actions Within Group" to get it to display images.  I tried this and it didn't work.  Still no images.

**Comment by Larkinabout** [comment]
Yeah, this was before realising that a PF2e system update had broken something.

**Comment by Larkinabout** [comment]
Fixed in 1.5.2.

**Comment by Kay9Cop** [comment]
Thank you!
