### ISSUE TITLE
Unable to access HUD after update

### ISSUE THREAD

**Issue by mkniller** [Larkinabout/fvtt-token-action-hud-pf2e#99]
Foundry V11 Stable 315
Pathfinder 2e 5.8.3
Token Action HUD Core 1.5.2
Token Action HUD Pathfinder 2e 1.5.2

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/8039354/07fceec6-55b6-4318-a4ea-dc284d5415d8)

After updating to 1.5.2 of both core and Pathfinder HUD I am unable to see the either module in the Game Settings, and when I try to activate the HUD on a player token it does not show up.  Token HUD was working with the previous release I had installed.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/8039354/b99b68aa-fbe9-4746-9eac-ca7969846fec)

**Comment by mkniller** [comment]
Reverted back to the last verison prior to 1.5.x and it is working.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/8039354/fd13dee3-7c6c-4665-abd2-35bd3d1ff2cc)

**Comment by mkniller** [comment]
Please see the first 4 lines of my first post... I am not running the latest version of Pathfinder, I am on the last version prior to the remaster release.

**Comment by Larkinabout** [comment]
I would just keep using the version that works. If you want to try to get the latest version working, open up the browser console and see if there are any errors mentioning Token Action HUD.
